#!/usr/bin/env python3

# The issue is with the JSON formatting - we need to ensure proper escaping
# Let's create a more controlled approach using json module

import json
import os
import collections
import torch
import numpy as np

# Define the notebook structure as a Python dictionary
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# TFT Model Evaluation (10-Second Bars)\n",
                "\n",
                "This notebook evaluates the performance of a Temporal Fusion Transformer model trained on 10-second bar data for cryptocurrency price prediction."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import glob\n",
                "import torch\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import psycopg2\n",
                "from datetime import datetime, timedelta\n",
                "from models.temporal_fusion_transformer import TemporalFusionTransformer, MarketDataset\n",
                "from torch.utils.data import DataLoader\n",
                "\n",
                "# Define a custom dataset for NumPy arrays\n",
                "class NumpyMarketDataset(torch.utils.data.Dataset):\n",
                "    def __init__(self, features, targets, context_length=10):\n",
                "        \"\"\"A simple dataset for handling NumPy feature arrays for the TFT model.\n",
                "        \n",
                "        Args:\n",
                "            features: NumPy array of shape (n_samples, n_features)\n",
                "            targets: NumPy array of shape (n_samples,)\n",
                "            context_length: Length of context window\n",
                "        \"\"\"\n",
                "        self.features = features\n",
                "        self.targets = targets\n",
                "        self.context_length = context_length\n",
                "        \n",
                "        # Calculate valid samples (need enough history for context window)\n",
                "        self.n_samples = max(0, len(features) - context_length)\n",
                "        \n",
                "    def __len__(self):\n",
                "        return self.n_samples\n",
                "    \n",
                "    def __getitem__(self, idx):\n",
                "        # Get window of data (idx to idx+context_length)\n",
                "        feature_window = self.features[idx:idx+self.context_length]\n",
                "        # Get target (the next value after the window)\n",
                "        target = self.targets[idx+self.context_length-1]  # Use the last value in window as target\n",
                "        \n",
                "        # Convert to tensors\n",
                "        feature_tensor = torch.tensor(feature_window, dtype=torch.float32)\n",
                "        target_tensor = torch.tensor(target, dtype=torch.float32).reshape(1)\n",
                "        \n",
                "        return feature_tensor, target_tensor\n",
                "\n",
                "# Configure plotting\n",
                "plt.style.use('ggplot')\n",
                "plt.rcParams['figure.figsize'] = (12, 8)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Database Connection\n",
                "\n",
                "Connect to the database to retrieve 10-second bar data."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Database configuration\n",
                "DB_CONFIG = {\n",
                "    'host': 'localhost',\n",
                "    'port': 5438,\n",
                "    'user': 'backtest_user',\n",
                "    'password': 'backtest_password',\n",
                "    'database': 'backtest_db'\n",
                "}\n",
                "\n",
                "# Connect to the database\n",
                "conn = psycopg2.connect(\n",
                "    host=DB_CONFIG['host'],\n",
                "    port=DB_CONFIG['port'],\n",
                "    user=DB_CONFIG['user'],\n",
                "    password=DB_CONFIG['password'],\n",
                "    database=DB_CONFIG['database']\n",
                ")\n",
                "\n",
                "print(\"Database connection established\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Data Loading\n",
                "\n",
                "Retrieve 10-second bar data from the database."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Query to get test data\n",
                "query = \"\"\"\n",
                "SELECT \n",
                "    timestamp,\n",
                "    open, high, low, close,\n",
                "    volume, bid_vol, ask_vol, imbalance, \n",
                "    spread_mean, spread_pct_mean,\n",
                "    new_bid_orders, new_ask_orders,\n",
                "    canceled_bid_orders, canceled_ask_orders,\n",
                "    executed_bid_orders, executed_ask_orders,\n",
                "    buy_sell_imbalance,\n",
                "    returns_10sec, returns_30sec, returns_1min,\n",
                "    volatility_1min, target_10sec as next_return\n",
                "FROM tft_features_10sec\n",
                "ORDER BY timestamp DESC\n",
                "LIMIT 10000;\n",
                "\"\"\"\n",
                "\n",
                "# Load data\n",
                "df = pd.read_sql_query(query, conn)\n",
                "print(f\"Loaded {len(df)} rows of 10-second bar data\")\n",
                "df = df.sort_values('timestamp')\n",
                "df.head()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Data Preparation\n",
                "\n",
                "Prepare the data for model evaluation."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Define feature columns\n",
                "feature_columns = [col for col in df.columns if col not in ['timestamp', 'next_return']]\n",
                "print(f\"Using {len(feature_columns)} features\")\n",
                "\n",
                "# Normalize features\n",
                "df_scaled = df.copy()\n",
                "for col in feature_columns:\n",
                "    mean_val = df[col].mean()\n",
                "    std_val = df[col].std()\n",
                "    \n",
                "    if std_val == 0:\n",
                "        print(f\"Feature {col} has zero std dev, setting to zero\")\n",
                "        df_scaled[col] = 0\n",
                "    else:\n",
                "        df_scaled[col] = (df[col] - mean_val) / std_val\n",
                "\n",
                "# Fill NaN values with zeros\n",
                "df_scaled = df_scaled.fillna(0)\n",
                "df_scaled['target'] = df_scaled['next_return']"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Model Loading\n",
                "\n",
                "Load the TFT model (with bias correction if available)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Check for bias-corrected models first\n",
                "bias_corrected_models = [f for f in os.listdir('models') \n",
                "                         if f.startswith('tft_10sec_bias_corrected_') and f.endswith('.pt')]\n",
                "\n",
                "if bias_corrected_models:\n",
                "    # Sort by timestamp (newest first)\n",
                "    bias_corrected_models.sort(reverse=True)\n",
                "    model_path = os.path.join('models', bias_corrected_models[0])\n",
                "    print(f\"Loading bias-corrected model: {model_path}\")\n",
                "    \n",
                "    # Load the model data\n",
                "    loaded_data = torch.load(model_path)\n",
                "    print(f\"Loaded data type: {type(loaded_data)}\")\n",
                "    \n",
                "    # Initialize a new model\n",
                "    model = TemporalFusionTransformer(\n",
                "        time_varying_features=21,  # Use exactly 21 features\n",
                "        hidden_size=128,  # IMPORTANT: Match the saved model architecture\n",
                "        num_heads=4,\n",
                "        dropout=0.2,\n",
                "        learning_rate=1e-4,\n",
                "        context_length=30,\n",
                "        prediction_length=1,\n",
                "        bias_correction=True\n",
                "    )\n",
                "    \n",
                "    # Get bias correction value (default 0.0002 if not found)\n",
                "    bias_correction = loaded_data.get('bias_correction', 0.0002)\n",
                "    print(f\"Using bias correction value: {bias_correction}\")\n",
                "    \n",
                "    # Check the type of model data and load appropriately\n",
                "    if 'model' in loaded_data:\n",
                "        model_data = loaded_data['model']\n",
                "        print(f\"Model data type: {type(model_data)}\")\n",
                "        \n",
                "        if isinstance(model_data, torch.nn.Module):\n",
                "            # It's already a model instance, use it directly\n",
                "            model = model_data\n",
                "            print(\"Using loaded model instance directly\")\n",
                "        elif isinstance(model_data, dict) or isinstance(model_data, collections.OrderedDict):\n",
                "            # Custom loading for mismatched architectures\n",
                "            print(\"Using custom parameter loading for different model architectures\")\n",
                "            \n",
                "            # Get current model state dict\n",
                "            current_state = model.state_dict()\n",
                "            \n",
                "            # Copy compatible parameters\n",
                "            compatible_params = 0\n",
                "            for param_name, param in current_state.items():\n",
                "                if param_name in model_data and param.shape == model_data[param_name].shape:\n",
                "                    # Copy parameter if name and shape match\n",
                "                    current_state[param_name] = model_data[param_name]\n",
                "                    compatible_params += 1\n",
                "                    print(f\"Loaded compatible parameter: {param_name}\")\n",
                "            \n",
                "            # Load the updated state dict\n",
                "            model.load_state_dict(current_state, strict=False)\n",
                "            print(f\"Loaded {compatible_params} compatible parameters from state dict\")\n",
                "            \n",
                "            # Now check if the feature_layer and final_layer were loaded\n",
                "            critical_layers = ['feature_layer.weight', 'feature_layer.bias', 'final_layer.0.weight', 'final_layer.0.bias']\n",
                "            for layer in critical_layers:\n",
                "                if layer in model_data and layer in current_state:\n",
                "                    print(f\"Critical layer '{layer}' was loaded correctly\")\n",
                "                else:\n",
                "                    print(f\"WARNING: Critical layer '{layer}' could not be loaded\")\n",
                "        else:\n",
                "            print(f\"WARNING: Unknown model data type {type(model_data)}, using new model\")\n",
                "    else:\n",
                "        # No 'model' key, try loading the whole thing as a state dict\n",
                "        try:\n",
                "            current_state = model.state_dict()\n",
                "            compatible_params = 0\n",
                "            \n",
                "            for param_name, param in current_state.items():\n",
                "                if param_name in loaded_data and param.shape == loaded_data[param_name].shape:\n",
                "                    current_state[param_name] = loaded_data[param_name]\n",
                "                    compatible_params += 1\n",
                "            \n",
                "            model.load_state_dict(current_state, strict=False)\n",
                "            print(f\"Loaded {compatible_params} compatible parameters from full data\")\n",
                "        except Exception as e:\n",
                "            print(f\"WARNING: Failed to load model data: {str(e)}\")\n",
                "    \n",
                "    # Put model in evaluation mode\n",
                "    model.eval()\n",
                "    print(f\"Model loaded with bias correction: {bias_correction}\")\n",
                "    \n",
                "    # Create a wrapper for bias correction\n",
                "    def predict_with_bias_correction(x):\n",
                "        with torch.no_grad():\n",
                "            raw_prediction = model(None, x)  # Pass None for static_features\n",
                "            return raw_prediction - bias_correction\n",
                "else:\n",
                "    # Try regular model files\n",
                "    regular_models = [f for f in os.listdir('models') \n",
                "                      if f.startswith('tft_10sec_model_') and f.endswith('.pt')]\n",
                "    \n",
                "    if regular_models:\n",
                "        regular_models.sort(reverse=True)\n",
                "        model_path = os.path.join('models', regular_models[0])\n",
                "        print(f\"Loading regular model: {model_path}\")\n",
                "        \n",
                "        # Load the data\n",
                "        loaded_data = torch.load(model_path)\n",
                "        print(f\"Loaded data type: {type(loaded_data)}\")\n",
                "        \n",
                "        # Initialize a new model\n",
                "        model = TemporalFusionTransformer(\n",
                "            time_varying_features=21,  # Use exactly 21 features\n",
                "            hidden_size=128,  # IMPORTANT: Match the saved model architecture\n",
                "            num_heads=4,\n",
                "            dropout=0.2,\n",
                "            learning_rate=1e-4,\n",
                "            context_length=30,\n",
                "            prediction_length=1\n",
                "        )\n",
                "        \n",
                "        # Handle different formats with custom loading\n",
                "        if hasattr(loaded_data, 'state_dict'):\n",
                "            # It's a model object\n",
                "            model = loaded_data\n",
                "            print(\"Using loaded model instance directly\")\n",
                "        else:\n",
                "            # Custom parameter loading for state dict\n",
                "            print(\"Using custom parameter loading for different model architectures\")\n",
                "            current_state = model.state_dict()\n",
                "            compatible_params = 0\n",
                "            \n",
                "            for param_name, param in current_state.items():\n",
                "                if param_name in loaded_data and param.shape == loaded_data[param_name].shape:\n",
                "                    current_state[param_name] = loaded_data[param_name]\n",
                "                    compatible_params += 1\n",
                "            \n",
                "            model.load_state_dict(current_state, strict=False)\n",
                "            print(f\"Loaded {compatible_params} compatible parameters from state dict\")\n",
                "        \n",
                "        # Put model in evaluation mode\n",
                "        model.eval()\n",
                "        \n",
                "        # No bias correction\n",
                "        def predict_with_bias_correction(x):\n",
                "            with torch.no_grad():\n",
                "                return model(None, x)  # Pass None for static_features\n",
                "    else:\n",
                "        print(\"No 10-second TFT models found\")\n",
                "        raise FileNotFoundError(\"No models found\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Creating Data Loaders"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Prepare data for the model\n",
                "X = df_scaled[feature_columns].values.astype(np.float32)\n",
                "y = df_scaled['target'].values.astype(np.float32)\n",
                "\n",
                "# Create dataset and dataloader\n",
                "context_length = 30\n",
                "dataset = NumpyMarketDataset(X, y, context_length=context_length)\n",
                "dataloader = DataLoader(dataset, batch_size=64, shuffle=False)\n",
                "\n",
                "print(f\"Created dataset with {len(dataset)} samples\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Generating Predictions"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Generate predictions\n",
                "actuals = []\n",
                "predictions = []\n",
                "timestamps = []\n",
                "\n",
                "# Skip first context_length points (they don't have enough history)\n",
                "valid_timestamps = df['timestamp'].values[context_length:]\n",
                "\n",
                "for i, (X_batch, y_batch) in enumerate(dataloader):\n",
                "    # Check for feature dimension mismatch\n",
                "    if X_batch.shape[2] != len(feature_columns):\n",
                "        print(f\"WARNING: Feature dimension mismatch. Expected {len(feature_columns)}, got {X_batch.shape[2]}\")\n",
                "        \n",
                "        # Handle mismatch by using only the first n features if needed\n",
                "        if X_batch.shape[2] > len(feature_columns):\n",
                "            X_batch = X_batch[:, :, :len(feature_columns)]\n",
                "    \n",
                "    # Make predictions with bias correction if available\n",
                "    pred_batch = predict_with_bias_correction(X_batch)\n",
                "    \n",
                "    # Store results\n",
                "    actuals.extend(y_batch.numpy().flatten())\n",
                "    predictions.extend(pred_batch.numpy().flatten())\n",
                "    \n",
                "    # Add timestamps\n",
                "    batch_size = len(y_batch)\n",
                "    start_idx = i * dataloader.batch_size\n",
                "    end_idx = min(start_idx + batch_size, len(valid_timestamps))\n",
                "    timestamps.extend(valid_timestamps[start_idx:end_idx])\n",
                "\n",
                "# Create results dataframe\n",
                "results_df = pd.DataFrame({\n",
                "    'timestamp': timestamps,\n",
                "    'actual': actuals,\n",
                "    'predicted': predictions\n",
                "})\n",
                "\n",
                "# Calculate metrics\n",
                "mae = np.mean(np.abs(results_df['actual'] - results_df['predicted']))\n",
                "rmse = np.sqrt(np.mean((results_df['actual'] - results_df['predicted'])**2))\n",
                "correlation = np.corrcoef(results_df['actual'], results_df['predicted'])[0, 1]\n",
                "\n",
                "print(f\"Evaluation metrics:\")\n",
                "print(f\"MAE: {mae:.6f}\")\n",
                "print(f\"RMSE: {rmse:.6f}\")\n",
                "print(f\"Correlation: {correlation:.6f}\")\n",
                "\n",
                "# Check for bias in predictions\n",
                "bias = np.mean(results_df['predicted'] - results_df['actual'])\n",
                "print(f\"Prediction bias: {bias:.6f}\")\n",
                "\n",
                "results_df.head()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Visualizations"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Plot actual vs predicted values\n",
                "plt.figure(figsize=(14, 7))\n",
                "plt.plot(results_df['timestamp'], results_df['actual'], label='Actual')\n",
                "plt.plot(results_df['timestamp'], results_df['predicted'], label='Predicted')\n",
                "plt.title('Actual vs Predicted Returns (10-second bars)')\n",
                "plt.xlabel('Time')\n",
                "plt.ylabel('Return')\n",
                "plt.legend()\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Zoomed view (100 points)\n",
                "window_size = 100\n",
                "start_idx = len(results_df) // 2\n",
                "window_df = results_df.iloc[start_idx:start_idx+window_size]\n",
                "\n",
                "plt.figure(figsize=(14, 7))\n",
                "plt.plot(window_df['timestamp'], window_df['actual'], label='Actual')\n",
                "plt.plot(window_df['timestamp'], window_df['predicted'], label='Predicted')\n",
                "plt.title('Actual vs Predicted Returns (Zoomed View)')\n",
                "plt.xlabel('Time')\n",
                "plt.ylabel('Return')\n",
                "plt.legend()\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Error distribution\n",
                "plt.figure(figsize=(10, 6))\n",
                "errors = results_df['predicted'] - results_df['actual']\n",
                "sns.histplot(errors, kde=True)\n",
                "plt.axvline(x=0, color='r', linestyle='--')\n",
                "plt.title('Prediction Error Distribution')\n",
                "plt.xlabel('Error')\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Trading Simulation\n",
                "\n",
                "Simulate a simple trading strategy based on the model's predictions."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Simple trading strategy\n",
                "def simulate_trading(df, threshold=0.0001, fee=0.001):\n",
                "    \"\"\"Simple trading simulation\"\"\"\n",
                "    position = 0  # 0=none, 1=long, -1=short\n",
                "    trades = []\n",
                "    \n",
                "    for i, row in df.iterrows():\n",
                "        pred = row['predicted']\n",
                "        \n",
                "        # Trading logic\n",
                "        if position == 0:  # No position\n",
                "            if pred > threshold:\n",
                "                position = 1\n",
                "                trades.append({'timestamp': row['timestamp'], 'action': 'buy', \n",
                "                              'pred': pred, 'actual': row['actual']})\n",
                "            elif pred < -threshold:\n",
                "                position = -1\n",
                "                trades.append({'timestamp': row['timestamp'], 'action': 'sell', \n",
                "                              'pred': pred, 'actual': row['actual']})\n",
                "        \n",
                "        elif position == 1:  # Long position\n",
                "            if pred < 0:\n",
                "                position = 0\n",
                "                trades.append({'timestamp': row['timestamp'], 'action': 'close_long', \n",
                "                              'pred': pred, 'actual': row['actual']})\n",
                "        \n",
                "        elif position == -1:  # Short position\n",
                "            if pred > 0:\n",
                "                position = 0\n",
                "                trades.append({'timestamp': row['timestamp'], 'action': 'close_short', \n",
                "                              'pred': pred, 'actual': row['actual']})\n",
                "    \n",
                "    if not trades:\n",
                "        print(\"No trades generated\")\n",
                "        return None\n",
                "        \n",
                "    # Create trades dataframe\n",
                "    trades_df = pd.DataFrame(trades)\n",
                "    \n",
                "    # Calculate PnL\n",
                "    pnl = []\n",
                "    cumulative = 0\n",
                "    \n",
                "    for i, trade in enumerate(trades_df.iterrows()):\n",
                "        if i == 0 or trades_df.iloc[i-1]['action'] in ['close_long', 'close_short']:\n",
                "            # Opening trade, no PnL yet\n",
                "            pnl.append(0)\n",
                "        else:\n",
                "            # Closing trade\n",
                "            prev_action = trades_df.iloc[i-1]['action']\n",
                "            direction = 1 if prev_action == 'buy' else -1\n",
                "            p = direction * trade[1]['actual'] - fee\n",
                "            pnl.append(p)\n",
                "            cumulative += p\n",
                "    \n",
                "    trades_df['pnl'] = pnl\n",
                "    trades_df['cumulative_pnl'] = np.cumsum(pnl)\n",
                "    \n",
                "    # Print statistics\n",
                "    win_count = (trades_df['pnl'] > 0).sum()\n",
                "    total_trades = len(trades_df)\n",
                "    win_rate = win_count / total_trades if total_trades > 0 else 0\n",
                "    \n",
                "    print(f\"Total trades: {total_trades}\")\n",
                "    print(f\"Win rate: {win_rate:.2%}\")\n",
                "    print(f\"Total PnL: {cumulative:.6f}\")\n",
                "    \n",
                "    return trades_df\n",
                "\n",
                "# Run simulation with different thresholds\n",
                "for threshold in [0.0001, 0.0002, 0.0003]:\n",
                "    print(f\"\\nSimulation with threshold {threshold}:\")\n",
                "    trades = simulate_trading(results_df, threshold=threshold)\n",
                "    \n",
                "    if trades is not None and len(trades) > 0:\n",
                "        plt.figure(figsize=(10, 6))\n",
                "        plt.plot(trades.index, trades['cumulative_pnl'])\n",
                "        plt.title(f'Cumulative PnL (threshold={threshold})')\n",
                "        plt.xlabel('Trade')\n",
                "        plt.ylabel('Cumulative PnL')\n",
                "        plt.grid(True)\n",
                "        plt.tight_layout()\n",
                "        plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Conclusion\n",
                "\n",
                "The 10-second TFT model allows for high-frequency prediction of price movements, capturing more short-term trading opportunities compared to models with longer timeframes.\n",
                "\n",
                "Key findings:\n",
                "- [Summarize performance metrics]\n",
                "- [Note any bias correction improvements]\n",
                "- [Trading strategy effectiveness]\n",
                "\n",
                "Next steps:\n",
                "1. Further optimize model parameters for high-frequency data\n",
                "2. Test more sophisticated trading strategies\n",
                "3. Compare with 1-minute model to quantify the advantages"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python (Quants)",
            "language": "python",
            "name": "quants-env"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook to file using proper JSON serialization
with open('evaluate_tft_10sec_model.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Evaluation notebook created: evaluate_tft_10sec_model.ipynb") 